name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Rodar agente CSPM
        run: python cspm_agente.py

      - name: Rodar agente DevSecOps
        run: python devsecops_agent.py
